### ISSUE TITLE
#1 Unable install npm modules

### ISSUE THREAD

**Issue by srichatala** [leocornus/angular-trac-client#2]
I cloned the application into my local and then trying to install npm to get bower components like angularjs, bootstrap, and jQuery. I am getting following error message.

If I append the angularjs, bootstrap css link individually it's working fine. 

![image](https://cloud.githubusercontent.com/assets/9619400/6784604/042c83e2-d157-11e4-98c4-18e7937ee463.png)

Plz help to install bower components to run applications.

**Comment by seanchen** [comment]
hi Sri,

that looks like your school proxy does NOT allow git protocol. the simple fix will be tell git to using https insteadof git:

```
$ cd angular-trac-client
$ git config url."https://".insteadof git://
```

I got the similar error when I try to set up angular-seed, [here is the details](https://github.com/seanchen/angular-seed/blob/master/troubleshoot.rst).

Please try and let me know

Thanks,

-Sean

**Comment by srichatala** [comment]
Thanks Sean,

Excellent, It's working perfectly fine.
